### PR TITLE
Reflection cache

### PR DESCRIPTION
**Pull request by karljj1**
Calling `GetMembers` is slow and generates a lot of garbage. This introduces a simple cache so that we only need to do the query once and then any subsequent queries can come from the cache. Its quite simple but gave a nice performance improvement and reduced the garbage by quite a lot for us :)

### CODE REVIEW

**Comment by axunonb** [comment]
Thanks, nice PR, will review this week.

**Comment by axunonb** [comment]
Did you measure the performance gain with the type cache?
My first rough test loop says performance doubled.

**Comment by karljj1** [comment]
I did test it on our version but I have not tested this one.

This was my results which also includes the object pooling. 
image

**Comment by axunonb** [comment]
Really great PR, thanks!

**Pull request merged**
